title: Good looks like this
email: dug@goodlookslikethis.com
description: >- # this means to ignore newlines until "baseurl:"
  Some of Dug's more interesting design things.
baseurl: "/devD" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: dug
github_username:  lrdj

# Build settings
# theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate

paginate: 7
paginate_path: "/blog/p:num/"

blogIndexSubtitles: true

# case footer links
case_footer_P_image: /i/address-book-metaphor.png
case_footer_N_image: /i/BM-report-C.png

collections:
  case_indices:
    output: true
    permalink: /cases/:name

defaults:
  -
    scope:
      type: "posts"
    values:
      author: "Dug Falby"
      layout: post
      bodyclass: single
  -
    scope:
      type: "case_indices"
    values:
      layout: caseindex
